name: ItemTagger
version: 1.1
authors: [Pangamma]
website: http://lumengaming.com/
main: itemtagger.ItemTagger
description: various name and description related things
commands:
  itemtagger:
    description: 'does everything.'
    usage: 'Usage: /<command>'
    aliases: ['it','tag','itag','gift','nbt','nt']
  sign:
    description: 'Signs an item with From: <from> To: <to>'
    usage: 'Usage: /sign <from> <to>'