name: ItemTagger
version: 1.1
authors: [Pangamma]
website: http://lumengaming.com/
main: itemtagger.ItemTagger
description: various name and description related things
commands:
  itemtagger:
    description: 'does everything.'
    usage: 'Usage: /<command>'
    aliases: ['it','tag','itag','gift','nbt','nt']
  sign:
    description: 'Directs a compass towards the nearest gemstone'
    usage: 'Usage: /<command>'