name: ItemTagger
version: 1.2
authors: [Pangamma, blha303]
website: http://lumengaming.com/
main: itemtagger.ItemTagger
description: Plugin for adding and modifying item metadata
commands:
  itemtagger:
    description: 'All ItemTagger commands'
    usage: 'ItemTagger help: /tag'
    aliases: ['it','tag','itag','gift','itemtag']
permissions:
  itemtagger.*:
    description: 'Allows access to /tag and all subcommands'
    children:
      itemtagger.name: true
      itemtagger.lore: true
      itemtagger.book: true
      itemtagger.heads: true
  itemtagger.name:
    description: 'Allows access to /tag set name'
    default: op
  itemtagger.lore:
    description: 'Allows access to /tag set lore and /tag add lore'
    default: op
  itemtagger.book:
    description: 'Allows access to /tag set author and /tag set title'
    default: op
  itemtagger.heads:
    description: 'Allows access to /tag set head'
    default: op